jbms/sphinx-immaterial

sphinx_immaterial/search_adapt.py
=> fix: Fix issue with search index that prevented incremental rebuilds

README.rst
The docs currently mentions the need to add `sphinx_immaterial` as an extension but this is missing from the README.
=> Add extension instruction to `README`

src/partials/tabs-item.html
I know nearly no HTML/CSS, so forgive my n00bness.
After the discussed in #31, I tested changes locally with my project. I found the "Main navigation item with nested items" `if` statement doesn't need to run.
https://github.com/jbms/sphinx-immaterial/blob/1597b3e8c81ee2834a152ba77ba833d667f32e8a/src/partials/tabs-item.html#L31-L48
Only the `else` statement needs to run.
https://github.com/jbms/sphinx-immaterial/blob/1597b3e8c81ee2834a152ba77ba833d667f32e8a/src/partials/tabs-item.html#L49-L56
Instead of deleting the `if` statement, I just set it to `false` to minimize merge conflicts with upstream.
=> Prevent navigation tabs linking to subsection

docs/customization.rst, sphinx_immaterial/nav_adapt.py
This resolves #39 and closes #37 
I updated the docs to guide users on how to hide a certain page's ToC and navigation menu. While I was updating customization.rst, I also added a hint about sphinx auto-implementing `navigation.indexes` feature from mkdocs-material.
=> support `hide` metadata and update docs

docs/customization.rst, src/assets/stylesheets/main/_api.scss
add rule to fix #35
I also added a note to close #33 (it was just a reminder issue anyway).
=> fix autosummary tables and add a note about tabs' toctree

docs/_static/extra_css.css, docs/admonitions.rst, docs/conf.py, docs/content_tabs.rst, docs/customization.rst, docs/index.rst, docs/mermaid_diagrams.rst, docs/requirements.txt, package-lock.json, setup.py, sphinx_immaterial/__init__.py, sphinx_immaterial/content_tabs.py, sphinx_immaterial/details_patch.py, sphinx_immaterial/mermaid_diagrams.py, src/assets/stylesheets/main.scss
These new directives are automatically added to doc builds because they are tied to our CSS:
- `md-tab-set` and `md-tab-item` which resolves #43 (includes a new doc page to demonstrate CSS `class`/`id` usage)
- `md-mermaid` to expose the implementation merged in from upstream (includes a new doc page to demonstrate CSS `class`/`id` usage).
- monkey-patch for the `sphinxcontrib-details-directive` which is applied only when the directive is installed. This patch allows us to use the `:class:` option to specify styling for collapsible admonitions. resolves #15 again
- updates _package.lock_ from changes in #44 
- auto-asserts line numbers as a table's column in code-blocks - resolves #26 until sphinx v6.0 is released
- removes dependency on `sphinx-design` in docs' builds, but adds …
=> Custom extensions

sphinx_immaterial/nav_adapt.py
If there are no toctree elements, no deeper node-walk
is performed anymore.
Fixes #51
=> Bugfix for small, 1-page projects

docs/customization.rst, sphinx_immaterial/__init__.py
This PR fixes #48 by properly assigning the `config` dictionary with the Google Analytics property value.
After some digging, I realized the Material for Mkdocs analytics code (partial) was not being added during local testing. The Google Analytics signaling I get on RTD is from custom JS added by RTD at build time.
Below is the partial looking for `config.extra.analytics`, which currently is not set.
https://github.com/jbms/sphinx-immaterial/blob/3b1a1a097d2923c7cd8736eb6509a0aca7d96aba/src/partials/integrations/analytics/google.html#L23-L30
I learned that the `google_analytics` configuration option has been deprecated in favor of `extra/analytics`. See [here](https://squidfunk.github.io/mkdocs-material/upgrade/?h=google+ana#google_analytics).
This PR reads the old configuration style …
=> Properly configure Google Analytics

sphinx_immaterial/nav_adapt.py
Fixes #62.
Thanks to @mhostetter for reporting.
=> Fix incorrect TOC collapsing

docs/cpp.rst, sphinx_immaterial/cpp_domain_fixes.py
=> Fix C++ parameter cross-linking for object descriptions with nested object descriptions

docs/api.rst, docs/conf.py, docs/cpp.rst, docs/demo_api.rst, docs/format_signatures.rst, requirements.txt, sphinx_immaterial/__init__.py, sphinx_immaterial/apidoc_formatting.py, sphinx_immaterial/cpp_domain_fixes.py, sphinx_immaterial/format_signatures.py, sphinx_immaterial/generic_synopses.py, sphinx_immaterial/nav_adapt.py, sphinx_immaterial/object_toc.py, sphinx_immaterial/sphinx_utils.py, src/assets/stylesheets/main/_api.scss
This replaces manny config options with a more general "object
description options" mechanism that allows various options to be
configured on a per domain/object type basis.
This commit also adds a number of features built on top of that mechanism:
- Generating object description synopses for the std domain, including
custom object types added using `app.add_object_type`.
- Excluding certain object types from the TOC
- Excluding the object type from the cross-reference tooltip.
Fixes #70.
=> Add object description options mechanism

src/assets/stylesheets/main/_api.scss
=> Fix styling of punctuation in signatures

docs/api.rst, docs/cpp.rst, docs/python.rst, sphinx_immaterial/cpp_domain_fixes.py, sphinx_immaterial/generic_synopses.py, sphinx_immaterial/python_domain_fixes.py
Note: This still requires some work --- this does not preserve parameter types specified outside of the signature, and does not gracefully handle invalid Python syntax as signatures, e.g. using brackets to indicate optional parameters.
=> Add Python synopsis and parameter cross-reference support

docs/python.rst, sphinx_immaterial/python_type_annotation_transforms.py
=> Fix concise literals with autodoc type hint shortening

.github/workflows/build.yml, requirements.txt, sphinx_immaterial/apidoc_formatting.py, sphinx_immaterial/sphinx_utils.py
This also adds a github actions build for Python 3.7, 3.8, and 3.10.
Fixes #84.
=> Use typing_extensions to support Python 3.7

src/assets/javascripts/sphinx_search.ts
Fixes #94
Removes redundant `/` when loading search-related resources.
=> Remove redundant "/" when loading search js

.github/workflows/build.yml
This PR modifies the GA workflow to build and upload `sdist` source distributions.
Closes #96.
=> Build and upload tarballs with sdist

docs/test_py_module/test.py, sphinx_immaterial/autodoc_property_type.py
This is a simple fix addressing the #104 by falling back to retrieving the `__doc__` directly from the `obj` if there is no `.fget` attribute available.
=> Tweaking patched PropertyDocumenter to support cached_property, fixes #104

sphinx_immaterial/content_tabs.py
fixes #108 by adding the missing/closing `</div>` tag
Apparently, the `depart_tab_set()` isn't called if `SkipNode` is raised. I left it in to please sphinx's `add_node()`.
=> ensure content tabs' elements are closed

sphinx_immaterial/apidoc/python/type_annotation_transforms.py, tests/python_transform_type_annotations_test.py
=> Fix Python type_annotation_transforms for Python<3.9

docs/apidoc/index.rst, sphinx_immaterial/apidoc/apidoc_formatting.py, sphinx_immaterial/apidoc/object_toc.py
Fixes #126. I believe I correctly implemented this feature. Please let me know your thoughts. I tested this locally on my project and on a standalone `foo` project.
The option is disabled by default. When enabled, all rubrics (that haven't already been converted to fields or admonitions by Napoleon) are added to the TOC. Here's an example in this `foo` module.  [foo-example.zip](https://github.com/jbms/sphinx-immaterial/files/9167987/foo-example.zip)
=> Add `include_rubrics_in_toc` object description option

docs/conf.py, docs/cpp_apigen_demo/array.h, docs/cpp_apigen_demo/index_interval.h, sphinx_immaterial/apidoc/cpp/api_parser.py, sphinx_immaterial/apidoc/cpp/apigen.py, tests/cpp_api_parser_test.py
Includes
- fix for Windows paths
- fix for unresolved cross-refs in the new docs
- support for `\` and `@` prefixed Doxygen commands
- support for `@retval` command
- support for param direction(s)
- add new `strip_comment()` to accommodate for all forms of C++ comment syntax
I also enabled verbosity in the cpp.apigen demo and added a line that shows the number of declarations that will be parsed.
=> Some cpp comment stripping parsing

src/assets/stylesheets/main/_typeset.scss
=> Ensure tables don't exceed content area width

sphinx_immaterial/apidoc/python/apigen.py, tests/python_apigen_test.py, tests/python_apigen_test_modules/_alpha.py, tests/python_apigen_test_modules/_bravo.py, tests/python_apigen_test_modules/issue147.py
=> Python apigen: Ensure correct `module` is specified

docs/conf.py, sphinx_immaterial/__init__.py, sphinx_immaterial/apidoc/apidoc_formatting.py, sphinx_immaterial/apidoc/cpp/parameter_objects.py, sphinx_immaterial/apidoc/cpp/synopses.py, sphinx_immaterial/apidoc/format_signatures.py, sphinx_immaterial/apidoc/generic_synopses.py, sphinx_immaterial/apidoc/json/domain.py, sphinx_immaterial/apidoc/object_description_options.py, sphinx_immaterial/apidoc/object_toc.py, sphinx_immaterial/apidoc/python/apigen.py, sphinx_immaterial/apidoc/python/domain_fixes.py, sphinx_immaterial/apidoc/python/parameter_objects.py, sphinx_immaterial/apidoc/python/subscript_methods.py, sphinx_immaterial/apidoc/python/synopses.py, sphinx_immaterial/apidoc/wrap_signatures.py, sphinx_immaterial/details_patch.py, sphinx_immaterial/html_translator_mixin.py, sphinx_immaterial/nav_adapt.py, sphinx_immaterial/sections.py, src/assets/stylesheets/main/_api.scss
Fixes #156.
This also refactors the various HTMLTranslator overrides.
=> Eliminate colon from headings in field lists

sphinx_immaterial/apidoc/cpp/api_parser.py, sphinx_immaterial/apidoc/cpp/fix_cpp_domain_symbol_resolution_through_type_aliases.py, sphinx_immaterial/apidoc/cpp/parameter_objects.py, sphinx_immaterial/apidoc/cpp/symbol_ids.py, sphinx_immaterial/apidoc/object_description_options.py, sphinx_immaterial/apidoc/object_toc.py, sphinx_immaterial/apidoc/python/object_ids.py
Looks like the latest release of Sphinx (v5.2.2) brought with it a few "tweaks" to their type hints.
This addresses just that.
=> update typing related to the cpp.apigen ext

.gitignore, docs/conf.py, docs/customization.rst, sphinx_immaterial/theme.conf
- add `social` option to theme.conf
- add description of `social` option to customization.rst
- also adds common venv folders to gitignore which makes it easier to use an isolated venv on local dev machine.
Special thanks to @mhostetter for bringing this to my attention!
=> add `social` icons theme option to docs

docs/conf.py, docs/customization.rst
I found in the partials/social.html template that social links can have a customized tooltip using a `name` field. This adds the relevant info and demos its usage in the docs.
Also resolves #148 by removing a confusing adjective (per user feedback).
=> Minor doc updates

docs/additional_samples.rst, sphinx_immaterial/apidoc/apidoc_formatting.py
Also un-comment the section in additional_samples.rst now that this patch addresses #46
Modified the production list example to use dot syntax grammar (and avoid unreferenced token warnings in the build log). I added use of the `:token:` role in production list example to better demonstrate the full utility of a production list.
=> patch visitor for production list directive

sphinx_immaterial/details_patch.py
Fixes #184 by adding the `dirhtml` builder in our monkeypatch of the sphinxcontrib-details-directive extension.
=> resolve #184

docs/customization.rst, sphinx_immaterial/nav_adapt.py
Allows integration of page comments using [giscus](https://giscus.app/) (which uses github's discussions feature). Only thing we needed was a `comments` meta data field to enable comments for a specific page. Everything else is done by the user in the docs project's template overrides, which is now documented with instructions in customization.rst.
Tested this on a separate repo of mine (hosted at RTD.org), and it seems to work. It will not work when the URL is a `file://`. So, there's a preview at the bottom of [this page](https://circuitpython-homie.readthedocs.io/en/trying-doc-comments/tutorials/openhab.html#adding-a-homie-dev-as-an-oh-thing).
=> doc use of Giscus; add comments meta data tag

src/assets/stylesheets/main/layout/_nav.scss
fixes #189 by using the inline CSS variable with fallback value inherited from upstream
=> adjust regressive z-index override from #171

sphinx_immaterial/custom_admonitions.py
For the `markdown_it` module used by `myst_parser` the text must be passed as explicit string.
This PR ensures the `title_text` from `self.default_title` in `custom_admonitions.py` is converted from `<class 'sphinx.locale._TranslationProxy'>` to string.
This PR fixed #196.
=> Fix #196 exception in MyST/markdown-it-py

.github/workflows/build.yml
CI failed due to setup-graphviz behavior on macOS, so we no longer use ts-graphviz/setup-graphviz in PR #181.
In [ts-graphviz/setup-graphviz@v1.2.0](https://github.com/ts-graphviz/setup-graphviz/releases/tag/v1.2.0), this issue has been resolved and we are now using it again.
=> Fix to use ts-graphviz/setup-graphviz again on CI

docs/apidoc/python/index.rst, docs/conf.py, docs/customization.rst, package.json, setup.py, sphinx_immaterial/__init__.py, sphinx_immaterial/css_and_javascript_bundles.py, sphinx_immaterial/custom_admonitions.py, sphinx_immaterial/external_resource_cache.py, sphinx_immaterial/google_fonts.py, sphinx_immaterial/graphviz.py, sphinx_immaterial/inline_icons.py, src/base.html, tools/build/index.ts, tools/build/transform/index.ts
- Use Google Fonts metadata to fetch all available variants
Previously, this theme retrieved a hardcoded list of font variants, as
specified by the mkdocs-material theme.  However, it was reported in #193
that some fonts do not have all of these variants, leading to an error
when trying to use such a font.
With this change, the precise list of variants for each font is used
by fetching the complete list of fonts and variants from the Google
Fonts API.
This commit also factors out the Google Fonts retrieval logic from
`external_resource_cache.py` into a separate `google_fonts.py` module.
Fixes #193.
- Refactor CSS and JavaScript bundle output and support source maps
This refactors the existing CSS bundling code in
`custom_admonitions.py` in the following ways:
- JavaScript bundling is …
=> Improve CSS/JavaScript bundling and fix miscellaneous issues

sphinx_immaterial/apidoc/cpp/api_parser.py
Previously, some fields were incorrectly specified as `ClassVar` when they were intended as instance variables not included as parameters to `__init__`.  In addition to being an incorrect type annotation, this led to failures on older versions of pydantic.
=> Fix api_parser.Config dataclass definition

sphinx_immaterial/custom_admonitions.py
This ensures it is not redundantly patched if the extension is loaded more than once in a given process (only really relevant for tests).
=> Move custom_admonitions monkey patching out of extension setup function

pyproject.toml, sphinx_immaterial/__init__.py, sphinx_immaterial/apidoc/cpp/api_parser.py, sphinx_immaterial/apidoc/cpp/apigen.py, sphinx_immaterial/apidoc/cpp/ast_fixes.py, sphinx_immaterial/apidoc/cpp/cpp_resolve_c_xrefs.py, sphinx_immaterial/apidoc/cpp/default.py, sphinx_immaterial/apidoc/fix_sphinx_issue_11147.py, sphinx_immaterial/apidoc/json/domain.py, sphinx_immaterial/apidoc/python/apigen.py, sphinx_immaterial/apidoc/python/default.py, sphinx_immaterial/apidoc/python/domain_fixes.py, sphinx_immaterial/apidoc/python/section_titles.py, sphinx_immaterial/custom_admonitions.py, sphinx_immaterial/external_resource_cache.py, sphinx_immaterial/sections.py
- Remove unused imports and enable unused-imports lint
-  Add monkey patch to fix source file/line number info for object descriptions
- This addresses the issue described at https://github.com/sphinx-doc/sphinx/pull/11147.
- Disable apidoc/python/section_titles monkey patch for Sphinx >= 5.3
- This is unnecessary due to
https://github.com/sphinx-doc/sphinx/issues/10887, which adds support
for section titles in all object description content.
=> Fix source info

.github/workflows/build.yml
Since sphinx-immaterial has a bunch of dependencies, the package can break despite not making any modification to the sources. Actually, software nowadays tends to break unless it is continuously maintained.
Since this repo was not modified in a month, CI was not triggered. The readme shows a green shield/badge. However, the fact is that CI is currently broken.
This PR adds an `schedule` trigger to the `build` workflow in order to ensure that breaking changes in the dependencies are caught soon, regardless of the activity in this repo.
=> ci: schedule twice a month

.github/workflows/build.yml
Currently, if any job of the matrix fails, all others are cancelled automatically. However, some versions of Python might work while other fail. Or some versions might works on some platforms but fail on others.
This PR unsets `fail-fast`, in order to allow all jobs to finish regardless of one or some of them failing.
=> ci: do not fail fast

sphinx_immaterial/apidoc/cpp/parameter_objects.py
Move the definition of param_id_suffix before the for loop to avoid
potential UnboundLocalError in case the for loop is never executed.
Signed-off-by: Benjamin Cabé <benjamin@zephyrproject.org>
=> Fix potential UnboundLocalError

sphinx_immaterial/apidoc/apidoc_formatting.py
The explicit `add_fignumber` adds rendering of another figure number, resulting in double Fig entries in rendered doc. In addition, for code listings the Listing appears as a raw text above the code block:
This PR removes the excessive number for tables and figures (code blocks require it). In addition, the Listing number, as well as listing caption are wrapped in `filename` class so they appear as listing content above the code block. The result is following:
=> Fixed double numfig statements for Figues and no listing number for code blocks

docs/index.rst
as mentioned in #238, here's a little docs extension for people who are switching from another theme. i made it collapsed by default as it could potentially grow. for now i'm setting my migration more or less aside, so that's all as first impression.
on that occasion, i think the docs could really benefit from a section for hackers. i noticed inconsistencies how admonitions are parsed and it took me a while to get a grip how i should set up a test for that. admittedly i'm not in best condition atm and then dealing with `docutils` is just too much of a pita.
=> Extends docs with hint when migrating

docs/admonitions.rst, sphinx_immaterial/custom_admonitions.py, src/assets/stylesheets/main/_sphinx.scss
resolves #243
This does not override the original sphinx directives `versionadded`, `versionchanged`, and `deprecated`. Rather, the CSS styles have been adjusted to render these directives as admonitions. The default styles can be customized using the custom admonitions feature, but only `color` and `icon` will apply (as long as the `name` matches the directive name).
Also adds the italicized style inherent in Sphinx' basic theme CSS.
Updated admonitions.rst accordingly.
=> Styling version directives

docs/additional_samples.rst, sphinx_immaterial/apidoc/object_toc.py
resolves #248
The problem doesn't seem instigated by any changes to docutils or sphinx. So, it may have been something that was originally overlooked in #157.
Use `rst-example` for the `glossary` directive in additional_samples.rst
=> remove unnecessary permalink to `depart_term()`

docs/admonitions.rst, sphinx_immaterial/custom_admonitions.css, sphinx_immaterial/custom_admonitions.py
The version directives now support admonition options including `collapsible`, `class`, and `name`.
Note `title` and `no-title` options are not supported because
1. the default title cannot be changed
2. the directives arguments (both required and optional) are used in the title
The custom admonitions feature's `classes` option is now also respected when set in conf.py.
=> support admonition options in version directives (follow-up to #246)

docs/conf.py
This a follow up to #256 that orders the colors as they are listed in the CSS bundle (according to hue).
The previous ordering was a bit chaotic because it was grabbing the color names from rules specifically for hyperlink elements. But, by only grabbing the color names from rules that define the fg/bg color vars, we get the originally expected results. Using a `list` structure also helps preserve the order as a `set` doesn't seem to guarantee the same order in which the items were added.
=> [docs] reorder palette color options

docs/conf.py, requirements.txt, requirements/dev-mypy.txt, sphinx_immaterial/apidoc/cpp/apigen.py, sphinx_immaterial/apidoc/object_description_options.py, sphinx_immaterial/custom_admonitions.css, sphinx_immaterial/custom_admonitions.py
resolves #268 
Also improves the color specification for custom admonitions by using the new `pydantic-extra-types` pkg. This means that the admonition color can be defined using a value compliant with CSS3 specs. Color transparency is ignored since all admonitions' colors use the same transparency (where applicable).
Pinned pydantic dependency to v2.0+ due to backward-incompatible changes (and better performance).
=> update for pydantic v2

tools/build/index.ts
resolves #279
Now includes all mathjax-needed files in the dist. This will also fix other features in the mathjax that optionally enabled (svg rendering).
=> include recommended assets for mathjax

sphinx_immaterial/nav_adapt.py, src/assets/stylesheets/main/_api.scss
Fix #289 
| before                                                                                              	| after                                                                                               	|
|-----------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------	|
| ![](https://github.com/jbms/sphinx-immaterial/assets/12596392/21ba1f5a-8f7f-4260-ba39-32f18e69910d) 	| ![](https://github.com/jbms/sphinx-immaterial/assets/12596392/7103fc77-0d72-4928-b0ea-84ed90bcfe11) 	|
=> force all objinfo icons to visually account for text's descender

.github/workflows/build.yml, CONTRIBUTING.md
Based on some discussion in #284
=> Contributing and CI Improvements

requirements.txt, sphinx_immaterial/custom_admonitions.py
This is problem that mypy picked up since the release of `pydantic-core` v2.10
I also pinned `pydantic-core` to v2.10 due the breaking change introduced there: https://github.com/pydantic/pydantic-core/pull/980
=> fix for pydantic-core for v2.10

sphinx_immaterial/custom_admonitions.py
Apparently this is backward compatible to v2.2, so there's no need to update our pinned pydantic version.
resolves #302
=> update namespace for pydantic API v2.5

src/assets/javascripts/sphinx_search.ts
Previously, the JavaScript search code split the search query only on spaces, which meant that with a search query of a compound word like "mkdocs-material", for example, would be treated as a single term "mkdocs-material".  In contrast, when building the search index, the `/\w+/` regexp is used to split compound words, such that the index would only contain "mkdoc" and "material" as separate terms. Consequently, "mkdocs-material" as a single term would never be found.
With this change, the JavaScript search query splitting has been changed to match what is done when building the index.
Fixes #262.
=> Fix the JavaScript search term splitting for compound words

docs/customization.rst, sphinx_immaterial/nav_adapt.py
=> enable edit-this-page button on RTD

merge_from_mkdocs_material.py
merge_from_mkdocs_material.py now uses git-rebase to the do the merge, which works better than `git apply --3way`.
=> Fix merge_from_mkdocs_material.py to handle renames

.github/workflows/build.yml, noxfile.py, requirements/dev-mypy.txt, requirements/dev-pylint.txt, tests/requirements-sphinx4.txt
fixes installed dependencies for tests using sphinx v4.x
Alternatively, we could deprecate sphinx v4, but I thought this would be more suitable for backward compatibility.
Also now includes python v3.12 in CI and unit tests.
=> Patch test deps for sphinx v4

.github/dependabot.yml
To automate updates for some dependencies, this PR enables github's dependabot for pip requirements.txt files and github actions used in CI workflows.
See [GH docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) for more detail.
=> create dependabot config

.github/workflows/build.yml, setup.py
- v4 of the actions/checkout uses node.js v20; v3 uses node.js v16. GH deprecated actions that use node.js v16.
- Includes minor fixes to avoid warnings from pypa/gh-action-pypi-publish (follow up to #316).
=> bump actions/checkout from 3 to 4; fix pypa/gh-action-pypi-publish warnings

docs/keys.rst
Noticed them while checking #325. Also, I realized that Sphinx can warn about underlines that are too short but ignore underlines that are too long.
=> Fix few title underlines

sphinx_immaterial/google_fonts.py, sphinx_immaterial/graphviz.py
=> Remove google fonts api key

.github/workflows/build.yml, src/assets/javascripts/sphinx_search.ts, src/assets/stylesheets/main/_sphinx.scss
resolves #312
I also noticed that the `npm run check` wasn't getting executed in CI; I think there were some changes in GH Actions' expressions about `contains()`.
=> add modded CSS from basic theme for footnotes/citations

docs/admonitions.rst, docs/apidoc/python/apigen.rst, docs/apidoc/python/index.rst, docs/conf.py, requirements/cpp.txt, requirements/dev-mypy.txt, sphinx_immaterial/apidoc/apigen_utils.py, sphinx_immaterial/apidoc/cpp/api_parser.py, sphinx_immaterial/apidoc/cpp/apigen.py, sphinx_immaterial/apidoc/cpp/cppreference.py, sphinx_immaterial/apidoc/cpp/fix_cpp_domain_symbol_resolution_through_type_aliases.py, sphinx_immaterial/apidoc/cpp/macro_parameters.py, sphinx_immaterial/apidoc/cpp/symbol_ids.py, sphinx_immaterial/apidoc/json/domain.py, sphinx_immaterial/apidoc/python/annotation_style.py, sphinx_immaterial/apidoc/python/apigen.py, sphinx_immaterial/apidoc/python/attribute_style.py, sphinx_immaterial/apidoc/python/autodoc_property_type.py, sphinx_immaterial/apidoc/python/strip_self_and_return_type_annotations.py, sphinx_immaterial/apidoc/python/style_default_values_as_code.py, sphinx_immaterial/apidoc/python/type_annotation_transforms.py, sphinx_immaterial/custom_admonitions.py, sphinx_immaterial/graphviz.py, sphinx_immaterial/kbd_keys.py, tests/extra_scope_test.py, tests/graphviz_test.py, tests/issue_134/issue_134_test.py, tests/python_transform_type_annotations_test.py, tests/requirements.txt, tests/system_fonts_test.py
=> Update for sphinx v7.3.x

docs/tensorstore_demo/__init__.py, docs/tensorstore_demo/_tensorstore.py, sphinx_immaterial/apidoc/python/apigen.py, sphinx_immaterial/apidoc/python/parameter_objects.py, tests/python_apigen_test.py, tests/python_apigen_test_modules/property.py
Previously, if the same function, method or property was assigned to an additional name in the same scope, it was documented as an independent entity.
With this change, it is documented together with the entity that it aliases as an additional signature.
=> Support methods/properties/functions that are aliased

sphinx_immaterial/apidoc/python/apigen.py, tests/python_apigen_test.py, tests/python_apigen_test_modules/property.py
Previously, if class ``A`` defined a member ``p`` with an alias ``q``, and then ``B`` inherits from ``A``, the ``q`` alias would be listed twice, since it would be added when processing the members of ``A`` and then again when processing the members of ``B``..
=> python/apigen: Fix inheritance of sibling/alias members

requirements/cpp.txt
sighingnow/libclang#71 seems to have been resolved. I'm unpinning libclang for MacOS.
=> unpin libclang on mac

sphinx_immaterial/apidoc/json/domain.py
resolves #274 by leveraging `sphinx.locale._` as a translation proxy.
Users will have to create .po files with the following phrases translated:
- "Required members"
- "Optional members"
=> allow translating English phrases in json domain output

.github/workflows/build.yml, README.rst, codecov.yml, docs/apidoc/json/domain.rst, docs/conf.py, noxfile.py, pyproject.toml, sphinx_immaterial/content_tabs.py, sphinx_immaterial/inlinesyntaxhighlight.py, tests/admonition_test.py, tests/code_annotations_test.py, tests/content_tabs_test.py, tests/inline_icon_test.py, tests/inline_syntax_highlight_test.py, tests/json_domain_test.py, tests/kbd_keys_test.py, tests/mermaid_test.py, tests/requirements.txt, tests/sitemap_test.py, tests/task_list_test.py, tests/theme_result_test.py
This adds unit tests for some of our simpler extensions. The `apidoc.*` and `external_resources` extensions still need some tests...
I mostly just used examples from the docs to create the new tests. This is a better measurement because unit tests are done in isolation, no other extensions complicate expected behavior.
I'm seeing a 7% increase in coverage in CI (compared to current main branch).
~As a continued avoidance of third-party services (like CodeCov), I also adjusted the CI workflow. Now, the coverage report's HTML output is uploaded to the gh-pages branch (in addition to Linux-built docs) upon push to main branch. Also, I added an entry to our docs' version selector for easy access to the latest coverage reports. This will help us see exactly which lines were invoked during unit …
=> Improve coverage reports

.github/workflows/build.yml, docs/test_py_module/test.py, noxfile.py, setup.py, sphinx_immaterial/apidoc/python/type_annotation_transforms.py
While Python 3.8 is not officially EOL, NumPy dropped Python 3.8 support with NumPy 1.25 released Jun 2023.
https://numpy.org/news/#numpy-1250-released
=> Drop Python 3.8 support

docs/conf.py, docs/python_apigen_demo.rst, docs/tensorstore_demo/__init__.py, docs/type_param_demo.py, sphinx_immaterial/apidoc/format_signatures.py, sphinx_immaterial/apidoc/object_description_options.py, sphinx_immaterial/apidoc/object_toc.py, sphinx_immaterial/apidoc/python/apigen.py, sphinx_immaterial/apidoc/python/object_ids.py, sphinx_immaterial/apidoc/python/parameter_objects.py, sphinx_immaterial/apidoc/python/synopses.py, sphinx_immaterial/apidoc/python/type_annotation_transforms.py, sphinx_immaterial/apidoc/python/type_param_utils.py, tests/python_type_param_utils_test.py
Sphinx has partial support for type parameter lists: they are supported by the Python domain in signatures, but are not supported by autodoc.
This adds the following support:
- Sphinx Python domain for type parameter fields in docstrings, with sphinx.ext.napoleon support as well.
- Support for type parameters as Sphinx objects, with cross-linking, like the existing support for function parameters as Sphinx objects.
- Support in apigen for PEP 695 type parameters, and for displaying pre-PEP 695 separately-defined TypeVar types as PEP 695 type parameters.
=> Add support for Python type parameter lists

sphinx_immaterial/apidoc/json/domain.py, tests/json_domain_test.py
Previously, this would incorrectly lead to an exception being thrown.
=> json: Fix bug with specifying maxItems but not minItems

docs/type_param_demo.py, sphinx_immaterial/apidoc/python/parameter_objects.py, tests/python_apigen_test.py, tests/python_apigen_test_modules/type_params.py
Previously, if a function introduced a type parameter, any references to that type parameter in the signature itself were correctly resolved. However, when documenting function parameters, the type from the signature is duplicated next to the parameter name, and any references to type parameters in these duplicated types were not correctly resolved.
This commit fixes that issue by applying the same resolution logic to the duplicated types.
=> apidoc/python: Fix xrefs to type parameters

.github/workflows/build.yml, noxfile.py, sphinx_immaterial/nav_adapt.py
using the 8.0.0rc1 from pypi
Thanks to awareness in sphinx-doc/sphinx#12629
=> support for Sphinx v8.0

docs/conf.py, noxfile.py, sphinx_immaterial/apidoc/cpp/api_parser.py, sphinx_immaterial/apidoc/cpp/apigen.py, sphinx_immaterial/apidoc/cpp/cpp_resolve_c_xrefs.py, sphinx_immaterial/apidoc/cpp/external_cpp_references.py, sphinx_immaterial/apidoc/format_signatures.py, sphinx_immaterial/apidoc/json/domain.py, sphinx_immaterial/apidoc/python/type_annotation_transforms.py, sphinx_immaterial/search_adapt.py, tests/cpp_api_parser_test.py, tests/cpp_apigen_test.py, tests/cpp_xref_c_domain_test.py
- Make C++ doc comment parsing more robust and don't rely on raw_comment from clang
- Fix handling of whitespace in format_signatures
- Remove unnecessary data from env to improve parallel build efficiency
- Fix building with Sphinx 8.0.2
- Fix C++ apigen handling of unnamed template parameters
- Fix `:any:` xrefs to C macros
- Support undocumented enumerators
=> Various fixes to C++ domain and format_signatures

sphinx_immaterial/apidoc/cpp/parameter_objects.py, sphinx_immaterial/apidoc/cpp/symbol_ids.py, sphinx_immaterial/apidoc/cpp/synopses.py, tests/cpp_domain_test.py, tests/snapshots/cpp_domain_test/test_macro_parameter_objects/references.txt, tests/snapshots/cpp_domain_test/test_parameter_objects/None/references.txt, tests/snapshots/cpp_domain_test/test_parameter_objects/abc/references.txt, tests/snapshots/cpp_domain_test/test_parameter_objects/empty/references.txt, tests/snapshots/cpp_domain_test/test_template_parameter_objects/references.txt
Previously, these were not properly taken into account by parameter objects.
=> Fix C/C++ domain support for :node-id: and :symbol-ids:

sphinx_immaterial/apidoc/python/apigen.py, tests/issue_134/sphinx-immaterial-pybind11-issue-134/sphinx_immaterial_pybind11_issue_134.cpp, tests/python_apigen_test.py, tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.bar_bool.json, tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.bar_int.json, tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.foo_bool.json, tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.foo_int.json
This was accidentally broken by
https://github.com/jbms/sphinx-immaterial/pull/357.
=> python/apigen: Fix support for pybind11 overloaded functions

sphinx_immaterial/apidoc/generic_synopses.py, sphinx_immaterial/apidoc/json/domain.py, sphinx_immaterial/apidoc/python/synopses.py, sphinx_immaterial/local_mathjax.py
Originally raised in #392 about Math domain. This adds type inference for monkey patched domain merge functions.
Offending commits in sphinx v8.1.0:
- https://github.com/sphinx-doc/sphinx/commit/d1c23a08a9d8b1fc77ad8c1a368c17b18e8fdc85
- https://github.com/sphinx-doc/sphinx/commit/76110c3ea05e4eef02bc1689c4b9253aca743392
=> fix: support for sphinx v8.1.0

sphinx_immaterial/apidoc/cpp/api_parser.py, tests/cpp_api_parser_test.py
Previously, the page names for variable template specializations incorrectly included the template arguments within angle brackets, unlike class template specializations where such arguments were stripped.
With this commit, template arguments are stripped and the entities are distinguished based on the user-specified `id`.
=> Fix C++ apigen page naming for variable template specializations

.stylelintrc, src/assets/stylesheets/main/layout/_nav.scss, tests/snapshots/format_signatures_test/test_format_signatures/py_function_astext.txt
Previously, when using navigation.tabs on non-leaf pages, the integrated TOC used for "layered" (mobile) navigation would incorrectly display as well. The fix in 87d87f900901ec56aff1df09572f68497bafcf31 was was not sufficient due to a CSS precedence issue, which is now corrected by using `!important`.
=> Fix navigation.tabs for non-leaf pages

src/assets/javascripts/sphinx_search.ts
A regular expression `/\w+/g` was added in PR #307, which broke the search for non-english words.
I changed it to `/\p{L}+/gu` to add support for all Unicode characters and removed redundant word boundary (`\b`) in highlight regex.
Fixes #399
=> Fix search term match and highlight for Unicode chars

sphinx_immaterial/apidoc/format_signatures.py, tests/format_signatures_test.py, tests/snapshots/format_signatures_test/test_format_signatures/py_function2_astext.txt
Previously, the format_signatures extension could result in pending_xref nodes with more than one child.  Sphinx assumes that pending_xref nodes only contain a single child, and if the reference fails to resolve, will discard all but the first child.
With this change, if there is more than one child to be added to a pending_xref node, they are wrapped in an `inline` node.
=> Fix pending_xref issue with format_signatures

sphinx_immaterial/apidoc/python/parameter_objects.py, tests/python_parameter_cross_link_test.py
Previously, Python parameters documented as `*args` or `**kwargs` (rather than just `args` or `kwargs`) did not get cross-linked properly.
Now, any leading `*` characters are ignored for the purpose of matching.
=> Ignore leading `*` characters in Python parameter names

docs/apidoc/format_signatures.rst, sphinx_immaterial/apidoc/wrap_signatures.py, src/templates/assets/stylesheets/main/_api.scss
Previously, specifying the maximum_signature_line_length option resulted in excessive blank lines within signatures due to undesired CSS dl/dd margin rule applicability.
Additionally, the `wrap_signatures_with_css` option, enabled by default, added redundant spacing.
This commit fixes dl/dd margin rules, and also disables `wrap_signatures_with_css` automatically when
`maximum_signature_line_length` is enabled.
Fixes https://github.com/jbms/sphinx-immaterial/issues/419.
=> Support maximum_signature_line_length Sphinx option

sphinx_immaterial/apidoc/format_signatures.py, tests/format_signatures_test.py, tests/snapshots/format_signatures_test/test_format_signatures/py_class_astext.txt, tests/snapshots/format_signatures_test/test_format_signatures/py_class_constructor_astext.txt, tests/snapshots/format_signatures_test/test_format_signatures/py_class_constructor_long_astext.txt
Previously, the format_signatures extension did not support the `class Foo(x: int = 3)` "constructor" syntax, which is not valid Python syntax, but is commonly used with Sphinx.
=> format_signatures(black): Support class constructor syntax

sphinx_immaterial/apidoc/format_signatures.py, tests/format_signatures_test.py, tests/snapshots/format_signatures_test/test_format_signatures/py_function3_astext.txt
Previously, format_signatures just called difflib.SequenceMatcher for alignment, which sometimes produced poor results, leading to broken pending_xref nodes.
This commit uses an improved algorithm that is faster and ensures alphanumeric characters are always perfectly aligned.
This commit also ensures that a failure to format is treated as a warning rather than error, and just skips formatting the individual signature that failed.
=> Fix alignment issue in format_signatures

sphinx_immaterial/mermaid_diagrams.py
Mermaid diagrams can be configured by a frontmatter block at the top of the diagram definition, e.g., for `classDiagram`:
```yaml
---
config:
class:
hideEmptyMembersBox: true
---
classDiagram
class Duck
```
https://mermaid.js.org/syntax/classDiagram.html#members-box
It doesn't work in sphinx-immaterial at the moment because `docutils.nodes.literal` changes spaces to `&nbsp` (`&#160;`) characters when parsing word tokens for highlighting, and then [frontmatter parsing in mermaid](https://github.com/mermaid-js/mermaid/blob/7b2083926dbe3b6280f42376a0d4195b2c72fb8e/packages/mermaid/src/diagram-api/frontmatter.ts#L33-L38) breaks.
That's why I've decided to change it `docutils.nodes.literal_block` with disabled highlighting. That way, the code of a diagram is passed to mermaid.js as is.
Output …
=> Fix parsing of frontmatter config in mermaid diagrams
