jbms/sphinx-immaterial

- .pylintrc
- sphinx_immaterial/search_adapt.py
- src/assets/javascripts/sphinx_search.ts
> Fixes sphinx_search.ts to work with the Sphinx 4.3 search index format

- requirements.txt
- sphinx_immaterial/nav_adapt.py
Fixes #49
I successfully tested this locally.
> Import `Markup()` from `markupsafe` instead of `jinja2`

- src/assets/javascripts/integrations/version/index.ts
> Fix detection of current version

- .gitattributes
- .github/workflows/build.yml
This fixes the version number issue https://github.com/jbms/sphinx-immaterial/pull/64#issuecomment-1107765536.
> Fix package version

- docs/cppreference.rst
- sphinx_immaterial/apidoc_formatting.py
> Small patches to #64 changes

- docs/demo_api.rst
- sphinx_immaterial/python_domain_fixes.py
> Fix cross-linking parameters in case of multiple signatures

- .pylintrc
- docs/api.rst
- docs/conf.py
- docs/demo_api.rst
- docs/format_signatures.rst
- docs/index.rst
- docs/index_transform_schema.yml
- docs/inheritance_schema.yml
- docs/json.rst
- docs/keys.rst
- docs/requirements.txt
- setup.py
- sphinx_immaterial/apidoc_formatting.py
- sphinx_immaterial/json_domain.py
- sphinx_immaterial/json_pprint.py
- sphinx_immaterial/sphinx_utils.py
- src/assets/stylesheets/main/_api.scss
Also adds
- "extras_require" entries to setup.py for the various optional dependencies.
- defaults for `object_description_options` regarding RST domain.
> Add json domain

- docs/api.rst
- docs/customization.rst
- docs/format_signatures.rst
resolves #81 and fixes a typo in a example snippet code block
> address #81

- sphinx_immaterial/cpp_domain_fixes.py
Fixes #100.
For the C++ autosummary extension, a different mechanism will need to
be used to identify the template parameters.
> Eliminate desc_cpp_template_params node

- .github/workflows/build.yml
- setup.py
- sphinx_immaterial/__init__.py
- sphinx_immaterial/nav_adapt.py
- tools/build/index.ts
> Support dirhtml builder

- sphinx_immaterial/__init__.py
> Fix base_url path for dirhtml builder

- docs/graphviz.rst
> Fix incorrect rst-example in docs/graphviz.rst

- sphinx_immaterial/apidoc/object_toc.py
> Restore include_rubrics_in_toc default to False

- sphinx_immaterial/apidoc/python/parameter_objects.py
- sphinx_immaterial/graphviz.py
- tests/python_apigen_test_modules/_alpha.py
- tests/python_apigen_test_modules/_bravo.py
- tests/python_apigen_test_modules/classmethod.py
The updates in mypy latest release started triggering errors in some files. This PR only addresses that.
> fix mypy errors

- src/partials/logo.html
> check for `logo_url` instead of `logo`

- sphinx_immaterial/apidoc/json/domain.py
- tests/json_domain_test.py
Also fix reporting of filename and line numbers in error messages.
> JSON domain: Don't treat unresolved $ref as fatal error

- sphinx_immaterial/apidoc/fix_sphinx_issue_11147.py
Needed for CI to pass on open PRs.
> type ignore assignment in fix_sphinx_issue_1147.py

- docs/conf.py
> update call to sphinx.util.typing.stringify in conf.py

- sphinx_immaterial/google_fonts.py
The Esbonio language server runs its own asyncio loop context when it invokes the Sphinx code.  This causes the asyncio.run() call to complain since it's already being run in the same thread.
Since we're already running a set of threads here using PoolExecutor, we can run one more thread which runs the asyncio.run() context in a separate thread.  This mitigates the interoperability issue with the Esbonio language server at the cost of an additional thread, and at the cost of blocking the coroutine loop within the Esbonio language server for the closing of the download set.
(See also swyddfa/esbonio#451)
> Fix interoperability with Esbonio language server (#163)

- docs/conf.py
- docs/customization.rst
- sphinx_immaterial/__init__.py
- sphinx_immaterial/theme.conf
> remove repo_type and make repo_name intuitive

- src/assets/stylesheets/main/_sphinx.scss
This PR closes #272. It adds CSS rules to fix an indentation issue in line blocks.
> Fix line block indentation issue

- sphinx_immaterial/custom_admonitions.py
see https://github.com/jbms/sphinx-immaterial/issues/280#issuecomment-1706427899
should resolve #280
> don't modify config on_build_init

- docs/customization.rst
- sphinx_immaterial/__init__.py
- sphinx_immaterial/theme.conf
satisfies #297 
Includes documentation and example snippets.
> Lang drop down

- docs/apidoc/python/apigen.rst
> apigen.rst: Adds missing character

- docs/_static/extra_css.css
- docs/index.rst
- docs/theme_result.rst
> doc theme_result extension

- docs/customization.rst
- sphinx_immaterial/google_fonts.py
> add config value to control font fetching max_workers

- docs/theme_result.rst
- fixes English grammar in 1 instance
- adds code snippet to complete admonished example
> proofreading theme_result.rst

- docs/customization.rst
Happy to add more details if needed.
Closes #380
> Add note about palette to toc.follow documentation

- sphinx_immaterial/__init__.py
Fixes https://github.com/jbms/sphinx-immaterial/issues/418.
> Warn if numpydoc extension is used

- docs/apidoc/cpp/apigen.rst
- docs/cpp_apigen_demo.rst
- sphinx_immaterial/nav_adapt.py
- src/templates/base.html
- src/templates/partials/content.html
- tests/genindex_test.py
Fixes https://github.com/jbms/sphinx-immaterial/issues/329
> Fix special pages like genindex

- sphinx_immaterial/nav_adapt.py
- tests/snapshots/nav_adapt_test/test_include_rubrics_in_toc/False/index.yml
- tests/snapshots/nav_adapt_test/test_include_rubrics_in_toc/True/index.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_False/a.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_False/b.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_False/c.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_False/index.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_True/a.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_True/b.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_True/c.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_False-includeonly_True/index.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_False/a.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_False/b.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_False/c.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_False/index.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_True/a.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_True/b.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_True/c.yml
- tests/snapshots/nav_adapt_test/test_nav/collapse_True-includeonly_True/index.yml
resolves #442
I'm not sure why the span was removed in #338
> wrap section titles in span element

- tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.bar_int.json
- tests/snapshots/python_apigen_test/test_pybind11_overloaded_function/Example.foo_int.json
> update test snapshots
